### ISSUE TITLE
Кривой плагин и яндексу до него дела нет.

### ISSUE THREAD

**Issue by Lolitop** [yandex-money/yandex-money-cms-shopscript5#9]
Поставили через фтп как говорит яндекс, в итоге плагин покрашил сайт и пришлось удалять, своими силами  исправили ошибку в коде!!!, в итоге все равно не работает выдает ошибку при оплате на сайте яндекс денег, мол в папке на фтп нет файла yamodulepayPayment.class.php , так где его взять если его и не было ???!!

**Comment by ostulov** [comment]
Добрый день!

Перед любыми действиями на сайте мы рекомендуем делать резервные копии. 
Если Вам необходима помощь в установке и настройке модуля, напишите на почту cms@yamoney.ru  с доступами к сайту.
